using System;
using UnityEngine;

namespace Propolis
{

    public enum PropolisStatus
    {
       OFF,ON,CORRUPTED,ULTRACORRUPTED,CLEANSER,RECIPE1,RECIPE2,RECIPE3,CLEANSING,WAVECORRUPTED,BLINKRECIPE1,BLINKRECIPE2, BLINKRECIPE3, SHIELD_ON,SHIELD_OFF
    }
}

